---
# tasks file for /home/ec2-user/ansible/roles/common
- name: Common Tasks
  ansible.builtin.debug:
    msg: Common Task Triggered

- name: Fix dpkg
  ansible.builtin.command: dpkg --configure -a

- name: Update apt
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp